language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - PREFER_LOWEST=0
  - PREFER_LOWEST=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

before_install:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer update --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

script:
  - vendor/bin/phpunit tests
